name: Build and upload APK to pre-release

on:
  push:
    branches:
      - master
      
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: microsoft
      - name: Build with Gradle
        run: ./gradlew assembleDebug
        
      - name: Create pre-release
        id: create_release
        uses: actions/create-release@v1.0.0
        with:
          tag_name: nightly
          release_name: Nightly Build
          prerelease: true

      - name: Upload APK to pre-release
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive

